<?php

namespace AppBundle\Repository;

/**
 * sysventuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sysventuryRepository extends \Doctrine\ORM\EntityRepository
{
}
